// ===== 家人名單 =====
// id 用英文或數字（不要重複、之後不要改，評分是用 id 記錄的）
// name 和 emoji 可以隨時改
// parent: true 的人可以「答應」或刪除任何人的願望
// email：開啟登入功能時，填這個人在 Firebase 建立的帳號（不需要是真的信箱，例如 dad@ourfamily.home）
const FAMILY = [
  { id: "dad", email: "dad@ourfamily.home", parent: true, name: "爸爸", emoji: "🧔" },
  { id: "mom", email: "mom@ourfamily.home", parent: true, name: "媽媽", emoji: "👩" },
  { id: "kid1", email: "kid1@ourfamily.home", name: "哥哥", emoji: "🦖" },
  { id: "kid2", email: "kid2@ourfamily.home", name: "妹妹", emoji: "🐰" },
];

// ===== 食譜 =====
// 新增一道菜：複製一整段 { ... }, 貼在最後面再改內容即可
// level：1 = 簡單、2 = 要一點耐心、3 = 請大人一起做
// subtitle：菜名下面的一行小字，可留空
// image：可留空（強烈建議放照片，版面以照片為主）。要放照片就把照片放進 images 資料夾，寫 "images/檔名.jpg"
// steps：每一步可以是文字，或 { text: "說明", image: "images/xxx.jpg" } 讓步驟附照片
const RECIPES = [
  {
    id: "tomato-egg",
    subtitle: "酸甜番茄配滑嫩炒蛋",
    title: "番茄炒蛋",
    from: "媽媽",
    emoji: "🍅",
    category: "家常菜",
    time: 15,
    level: 1,
    serves: 3,
    image: "",
    ingredients: ["番茄 2 顆", "雞蛋 3 顆", "蔥 1 根", "糖 1 小匙", "鹽 少許", "油 2 大匙"],
    steps: [
      "番茄切成小塊，蔥切成蔥花。",
      "把蛋打進碗裡，加一點點鹽，用筷子打散。",
      "請大人開火，鍋子熱了加油，倒入蛋液，炒到半熟就先盛起來。",
      "同一個鍋子放番茄，炒到出汁變軟，加糖和鹽。",
      "把蛋倒回去一起拌炒，撒上蔥花就完成了！",
    ],
    tip: "番茄炒久一點會比較甜，湯汁拌飯超好吃。",
  },
  {
    id: "braised-pork-rice",
    subtitle: "紅蔥酥香滷五花，淋在白飯上",
    title: "阿嬤的滷肉飯",
    from: "阿嬤",
    emoji: "🍚",
    category: "飯麵",
    time: 90,
    level: 3,
    serves: 6,
    image: "",
    ingredients: ["豬五花絞肉 600 克", "紅蔥酥 3 大匙", "醬油 6 大匙", "冰糖 1 大匙", "米酒 2 大匙", "五香粉 少許", "水 適量", "白飯"],
    steps: [
      "請大人把鍋子燒熱，放入絞肉炒到變色出油。",
      "加入紅蔥酥炒香。",
      "倒入醬油、米酒、冰糖和五香粉，翻炒均勻。",
      "加水蓋過肉，轉小火慢慢滷 1 個小時，中間記得攪一攪。",
      "滷到湯汁變濃，淋在白飯上。",
    ],
    tip: "隔天再吃會更入味，阿嬤都會多煮一鍋。",
  },
  {
    id: "corn-soup",
    subtitle: "牛奶玉米湯底與蛋花",
    title: "玉米濃湯",
    from: "爸爸",
    emoji: "🌽",
    category: "湯",
    time: 25,
    level: 2,
    serves: 4,
    image: "",
    ingredients: ["玉米醬罐頭 1 罐", "玉米粒 半杯", "雞蛋 1 顆", "牛奶 300 毫升", "水 300 毫升", "太白粉 1 大匙（加 2 大匙水調開）", "鹽 少許"],
    steps: [
      "把水、牛奶、玉米醬、玉米粒倒進鍋子裡。",
      "請大人開中火，邊煮邊攪拌，煮到冒小泡泡。",
      "慢慢倒入太白粉水，一直攪，湯會變濃稠。",
      "把蛋打散，繞圈圈倒進湯裡，就會變成漂亮的蛋花。",
      "加鹽調味，盛到碗裡。",
    ],
    tip: "撒一點黑胡椒或放一片奶油，味道更香。",
  },
  {
    id: "weekend-pancake",
    subtitle: "蓬鬆煎餅佐蜂蜜或果醬",
    title: "週末鬆餅",
    from: "爸爸",
    emoji: "🥞",
    category: "點心",
    time: 30,
    level: 2,
    serves: 4,
    image: "",
    ingredients: ["低筋麵粉 150 克", "泡打粉 1 小匙", "雞蛋 1 顆", "牛奶 150 毫升", "糖 2 大匙", "融化奶油 15 克", "蜂蜜或果醬"],
    steps: [
      "麵粉和泡打粉一起過篩到大碗裡。",
      "另一個碗把蛋、牛奶、糖攪勻，再加入融化奶油。",
      "把蛋奶液倒進麵粉裡，輕輕拌到沒有乾粉就好，不要拌太久。",
      "請大人用小火熱平底鍋，舀一勺麵糊倒進去。",
      "表面冒出很多小洞時翻面，再煎 1 分鐘。",
      "疊高高，淋上蜂蜜或果醬。",
    ],
    tip: "麵糊有一點小顆粒沒關係，這樣鬆餅才會蓬鬆。",
  },
  {
    id: "scallion-noodles",
    subtitle: "現炸蔥油與醬油拌麵",
    title: "蔥油拌麵",
    from: "媽媽",
    emoji: "🍜",
    category: "飯麵",
    time: 15,
    level: 2,
    serves: 2,
    image: "",
    ingredients: ["麵條 2 人份", "蔥 3 根", "油 3 大匙", "醬油 2 大匙", "糖 1 小匙"],
    steps: [
      "蔥切成小段。",
      "請大人在小鍋裡熱油，放蔥段用小火炸到金黃，蔥油就做好了。",
      "在碗裡放醬油和糖。",
      "麵條煮熟撈起，放進碗裡。",
      "淋上蔥油，拌一拌就可以吃了。",
    ],
    tip: "熱油很燙，一定要讓大人來倒。",
  },
  {
    id: "fruit-yogurt",
    subtitle: "新鮮水果、穀片與蜂蜜",
    title: "水果優格杯",
    from: "哥哥",
    emoji: "🍓",
    category: "點心",
    time: 10,
    level: 1,
    serves: 2,
    image: "",
    ingredients: ["原味優格 1 盒", "草莓或香蕉 隨意", "穀片 2 大匙", "蜂蜜 1 小匙"],
    steps: [
      "水果洗乾淨，用兒童刀切成小塊。",
      "在透明杯子裡先放一層優格。",
      "再放一層水果、一層穀片。",
      "重複疊到杯子滿滿的。",
      "最上面淋一點蜂蜜。",
    ],
    tip: "用透明杯子，看得到一層一層最漂亮。",
  },
];
